---
- hosts: adoctor_check_executor_hosts # Define Execution Host Range
  gather_facts: no # Do not collect facts during the execution to improve the execution speed.
  user: aops # Execution user
  vars_files:
    - "../vars/adoctor_check_executor_vars.yml"
  vars:
    install_adoctor_check_executor: true # Install adoctor_check_executor
    config_adoctor_check_executor: true # Config adoctor_check_executor
    start_adoctor_check_executor: true # Auto start adoctor_check_executor service
    create_user: False # Create user
  roles:
    - ../roles/adoctor_check_executor # Install adoctor_check_executor
