---
- hosts: adoctor_diag_executor_hosts # Define Execution Host Range
  gather_facts: no # Do not collect facts during the execution to improve the execution speed.
  user: aops # Execution user
  vars_files:
    - "../vars/adoctor_diag_executor_vars.yml"
  vars:
    install_adoctor_diag_executor: true # Install adoctor_diag_executor
    config_adoctor_diag_executor: true # Config adoctor_diag_executor
    start_adoctor_diag_executor: true # Auto start adoctor_diag_executor service
    create_user: False # Create user
  roles:
    - ../roles/adoctor_diag_executor # Install adoctor_diag_executor
