---
- hosts: gala_gopher_hosts # Define Execution Host Range
  gather_facts: no # Do not collect facts during the execution to improve the execution speed.
  become: true
  become_user: root
  # user:  # Execution user
  vars_files:
    - "../vars/gala_gopher_vars.yml"
  vars:
    install_gala_gopher: true # Install gala_gopher
    config_gala_gopher: true # Config gala_gopher
    start_gala_gopher: true # Start gala_gopher service
    create_user: False # Add gala_gopher user
  roles:
    - ../roles/gala_gopher # Install gala_gopher
