---
- hosts: gala_spider_hosts # Define Execution Host Range
  gather_facts: no # Do not collect facts during the execution to improve the execution speed.
  become: true
  become_user: root
  vars_files:
    - "../vars/gala_spider_vars.yml"
  vars:
    install_gala_spider: true # Install gala_spider
    config_gala_spider: true # Config gala_spider
    start_gala_spider: true # Start gala_spider service
    create_user: False # Add gala_spider user
  roles:
    - ../roles/gala_spider # Install gala_spider
