---
- hosts: kafka_hosts # Define Execution Host Range
  gather_facts: no # Do not collect facts during the execution to improve the execution speed.
  user: aops # Execution user
  vars_files:
    - "../vars/kafka_vars.yml"
  vars:
    install_kafka: true # Install kafka
    config_kafka: true # Config kafka
    start_service: true # Auto start kafka service
    create_user: False # Add kafka user
  roles:
    - ../roles/kafka # Install kafka

