---
- hosts: read_config_hosts
  gather_facts: no # Do not collect facts during the execution to improve the execution speed.
  user: aops # Execution user
  vars_files:
    - "../vars/read_config_vars.yml"
  roles:
    - ../roles/read_config
