---
- hosts: zookeeper_hosts # Define Execution Host Range
  gather_facts: no # Do not collect facts during the execution to improve the execution speed.
  user: aops # Execution user
  vars_files:
    - "../vars/zookeeper_vars.yml"
  vars:
    install_zk: true # Install zookeeper
    config_zk: true # Config zookeeper
    start_service: true # Start zookeeper service
    create_user: False # Add zookeeper user
  roles:
    - ../roles/zookeeper # Install zookeeper
