---
- name: Create diag_scheduler.ini and system.ini
  become: true
  become_user: root
  template: 
    src: "{{ item.src }}"
    dest: "{{ diag_scheduler_conf_dir }}/{{ item.dst }}"
    owner: root 
    group: root 
    mode: 0644 
    backup: yes
  with_items :
    - {src: diag_scheduler.ini.j2, dst: diag_scheduler.ini }
    
- name: Check firewalld status
  command: systemctl is-active firewalld
  ignore_errors: yes
  register: diag_firewalld

- name: Open firewall port of diag_scheduler
  become: true
  become_user: root
  firewalld:
    port: "{{ diag_scheduler_port }}/tcp"
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
  when: diag_firewalld.rc == 0