# Checking the Service Status
- name: Start adoctor_diag_scheduler
  become: true
  become_user: root
  service:
    name: adoctor-diag-scheduler
    state: restarted

# Checking the Service Status
- name: verify adoctor_diag_scheduler is listening on {{ diag_scheduler_port }}
  wait_for: port={{ diag_scheduler_port }} timeout=1
