---
- name: Change owner of files
  become: true
  become_user: "{{ user }}"
  file: dest={{ item }} owner={{ user }} group={{ user }} recurse=yes
  with_items:
    - "{{ install_dir }}"

- name: Create server.properties file
  become: true
  become_user: "{{ user }}"
  template: src=server.properties.j2 dest={{ install_dir }}/config/server.properties owner={{ user }} group={{ group }} mode=0644 backup=yes
