---
- name: Repo config for kafka
  become: true
  become_user: root
  yum_repository:
    name: "{{ repo_name }}"
    baseurl: "{{ repo_base_url }}"
    enabled: yes
    description: "{{ repo_description }}"
    mode: 0644
    gpgcheck: no
    file: "{{ repo_file }}"
    state: present

- name: Install packages
  become: true
  become_user: root
  dnf:
    state: present
    name:
      - kafka

- name: Create Data Dir
  become: true
  become_user: "{{ user }}"
  file: path={{ item }} state=directory owner={{ user }} group={{ group }} mode=0755
  with_items:
    - "{{ install_dir }}/{{ kafka_log_path }}"
