---
- name: Install Kafka
  include: install_kafka.yml
  when: install_kafka

- name: Config Kafka
  include: config_kafka.yml
  when: config_kafka

- name: Start Kafka
  include: start_kafka.yml
  when: start_service
