#Start kafka service
- name: Start kafka
  become: true
  become_user: "{{ user }}"
  service:
    name: kafka
    state: restarted

# Checking the Service Status
- name: Verify kafka is listening on {{ kafka_port }}
  wait_for: host={{ ansible_host }} port={{ kafka_port }} delay=10 timeout=20
