# Checking the Service Status
- name: Start Kafka
  shell: "cd {{ install_dir }}/bin && ./kafka-server-start.sh -daemon ../config/server.properties"
  become: yes
  become_user: "{{ user }}"

# Checking the Service Status
- name: Verify kafka is listening on {{ kafka_port }}
  wait_for: host={{ ansible_host }} port={{ kafka_port }} delay=10 timeout=20
