# Checking the Service Status
- name: Start Zookeeper
  become: true
  become_user: "{{ user }}"
  service:
    name: zookeeper
    state: started

# Checking the Service Status
- name: Verify zookeeper is listening on {{ client_port }}
  wait_for: port={{ client_port }} timeout=1
