---
- name: Create check_executor.ini and system.ini
  become: true
  become_user: root
  template: 
    src: "{{ item.src }}"
    dest: "{{ check_executor_conf_dir }}/{{ item.dst }}"
    owner: root 
    group: root 
    mode: 0644 
    backup: yes
  with_items :
    - {src: check_executor.ini.j2, dst: check_executor.ini }
