---
- name: Create check_scheduler.ini and system.ini
  become: true
  become_user: root
  template: 
    src: "{{ item.src }}"
    dest: "{{ check_executor_conf_dir }}/{{ item.dst }}"
    owner: root 
    group: root 
    mode: 0644 
    backup: yes
  with_items :
    - {src: check_scheduler.ini.j2, dst: check_scheduler.ini }
    - {src: system.ini.j2, dst: system.ini }

- name: Check firewalld status
  command: systemctl is-active firewalld
  ignore_errors: yes
  register: check_firewalld

- name: Open firewall port of check_scheduler
  become: true
  become_user: root
  firewalld:
    port: "{{ check_scheduler_port }}/tcp"
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
  when: check_firewalld.rc == 0