---
- name: Repo config for elasticsearch
  become: true
  become_user: root
  yum_repository:
    name: "{{ repo_name }}"
    baseurl: "{{ repo_base_url }}"
    enabled: yes
    description: "{{ repo_description }}"
    gpgkey: "{{ repo_gpgkey }}"
    mode: 0644
    file: "{{ repo_file }}"
    state: present

- name: Install packages
  become: true
  become_user: root
  dnf:
    state: latest
    name:
      - elasticsearch 
