# Checking the Service Status
- name: Start the service.
  become: true
  become_user: "{{ user }}"
  service:
    name: elasticsearch
    state: restarted

# Checking the Service Status
- name: Verify elasticsearch is listening on {{ elasticsearch_listen_port }}
  wait_for: host={{ elasticsearch_network_host }}  port={{ elasticsearch_listen_port }} timeout=1
