---
- name: Install Mysql
  include: install_mysql.yml
  when: install_mysql

- name: Config Mysql
  include: config_mysql.yml
  when: config_mysql

- name: Start Mysql
  include: start_mysql.yml
  when: start_mysql
