---
- name: Create prometheus.yml
  become: true
  become_user: "{{ user }}"
  template: src=prometheus.yml.j2 dest={{ prometheus_conf_dir }}/prometheus.yml  owner={{ user }} group={{ group }} mode=0644 backup=yes
