---
- name: Install Prometheus
  include: install_prometheus.yml
  when: install_prometheus

- name: Config prometheus
  include: config_prometheus.yml
  when: config_prometheus

- name: Start prometheus
  include: start_prometheus.yml
  when: start_prometheus
