# Checking the Service Status
- name: Start prometheus
  become: true
  become_user: "{{ user }}"
  service:
    name: prometheus
    state: restarted

# Checking the Service Status
- name: verify prometheus is listening on {{ prometheus_listen_port }}
  wait_for: port={{ prometheus_listen_port }} timeout=1
