---
- name: Copy history format Shell
  become: true
  become_user: root
  copy: src={{ item }} dest=/etc/profile.d/{{ item }} mode=0755 owner=root group=root backup=yes
  with_items: "{{ change_history_format_scripts }}"
  when: change_history_format

- name: Set history format
  shell: "source /etc/profile"
  become: yes
  become_user: root
  when: change_history_format

- name: Copy dmesg format Shell
  become: true
  become_user: root
  template: src={{ change_dmesg_format_scripts }} dest=/tmp/{{ change_dmesg_format_scripts }} mode=0755 owner=root group=root backup=yes
  when: change_dmesg_format

- name: Set dmesg format
  shell: "sh /tmp/{{ change_dmesg_format_scripts }}"
  become: yes
  become_user: root
  when: change_dmesg_format

- name: Create config dir
  become: true
  become_user: "{{ user }}"
  file: path={{ fluentd_config_dir }} state=directory owner={{ user }} group={{ group }} mode=0755

- name: Copy config file
  become: true
  become_user: "{{ user }}"
  template: src=fluent.conf.j2 dest={{ fluentd_config_dir }}/fluent.conf mode=0644 owner={{ user }} group={{ group }} backup=yes

- name: Init fluentd
  become: true
  become_user: "{{ user }}"
  shell: "fluentd --setup {{ fluentd_config_dir }}"
