---
- name: Create a directory if it does not exist
  file:
      path: /opt/spider
      state: directory
      mode: '755'

- name: Deploy gala-spider.yml
  template: src=templates/gala-spider.conf.j2 dest={{ install_dir }}/gala-spider.conf mode=0755
