# Checking the Service Status
- name: Start gala spider
  become: true
  become_user: root
  service:
    name: gala-spider
    state: started

# Checking the Service Status
- name: Verify gala spider is listening on {{ gala_spider_port }}
  wait_for: 
    delay=10
    port={{ gala_spider_port }}
    timeout=20
