---
- name: Check firewalld status
  command: systemctl is-active firewalld
  ignore_errors: yes
  register: check_firewalld

- name: Open firewall port of node_exporter
  become: true
  become_user: root
  firewalld:
    port: "{{ node_exporter_listen_port }}/tcp"
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
  when: check_firewalld.rc == 0
