# Checking the Service Status
- name: Start node_exporter
  become: true
  become_user: "{{ user }}"
  service:
    name: node_exporter
    state: restarted

# Checking the Service Status
- name: verify node_exporter is listening on {{ node_exporter_listen_port }}
  wait_for: port={{ node_exporter_listen_port }} timeout=1
