---
- name: Create diag_executor.ini and system.ini
  become: true
  become_user: root
  template: 
    src: "{{ item.src }}"
    dest: "{{ diag_executor_conf_dir }}/{{ item.dst }}"
    owner: root 
    group: root 
    mode: 0644 
    backup: yes
  with_items :
    - {src: diag_executor.ini.j2, dst: diag_executor.ini }
    - {src: system.ini.j2, dst: system.ini }