---
- name: Check firewalld status
  command: systemctl is-active firewalld
  ignore_errors: yes
  register: check_firewalld

- name: Open firewall port of gala-ragdoll
  become: true
  become_user: root
  firewalld:
    port: "{{ gala_ragdoll_port }}/tcp"
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
  when: check_firewalld.rc == 0