---

- name: Install gala_ragdoll
  include: install_gala_ragdoll.yml
  when: install_gala_ragdoll

- name: Config gala_ragdoll
  include: config_gala_ragdoll.yml
  when: config_gala_ragdoll

- name: Start gala_ragdoll
  include: start_gala_ragdoll.yml
  when: start_gala_ragdoll



