global:
    data_source: "prometheus"
    observe_conf_path: /etc/spider/observe.yaml

kafka:
    topic: gala_gopher
    broker: ["1.1.1.1:9092"]
    group_id: group_id

prometheus:
    base_url: "http://localhost:9090/"
    instant_api: "/api/v1/query"
    range_api: "/api/v1/query_range"
    step: 1

spider:
    port: 11115
    log_conf:
        log_path: "/var/log/gala-spider/spider.log"
        # log level: DEBUG/INFO/WARNING/ERROR/CRITICAL
        log_level: INFO
        # unit: MB
        max_size: 10
        backup_count: 10
