global:
    data_source: "prometheus"
    observe_conf_path: /etc/spider/observe.yaml

kafka:
    topic: gala_gopher
    broker: ["1.1.1.1:9092"]
    group_id: group_id

prometheus:
    base_url: "http://localhost:9090/"
    instant_api: "/api/v1/query"
    range_api: "/api/v1/query_range"
    step: 1

spider:
    port: 11115

anomaly_detection:
    tcp_link:
        detection_model_type: EXPERT_MODEL
        detection_attributes:
            retran_packets: {detection_interval: 5, threshold: 0, method: ">="}
            lost_packets: {detection_interval: 5, threshold: 0, method: ">="}
