global:
    data_source: "prometheus"
    observe_conf_path: /etc/spider/observe.yaml

prometheus:
    base_url: "http://10.137.16.165:9090/"
    instant_api: "/api/v1/query"
    range_api: "/api/v1/query_range"
    step: 1

spider:
    port: 11115
    log_conf:
        log_path: "/var/log/gala-spider/spider.log"
        # log level: DEBUG/INFO/WARNING/ERROR/CRITICAL
        log_level: INFO
        # unit: MB
        max_size: 10
        backup_count: 10

storage:
    # unit: minute
    period: 1
    database: arangodb
    db_conf:
        url: "http://localhost:8529"
        db_name: "spider"
