data_agent: gala_gopher
observe_entities:
  -
    type: host
    keys:
      - machine_id
    labels:
      - &host_name hostname
    name: *host_name
    metrics: []
    level: HOST
    dependingitems:
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: host
  -
    type: container
    keys:
      - container_id
      - machine_id
    labels:
      - &container_name container_name
      - ns
      - pid
    name: *container_name
    metrics:
      - memory.usage_in_bytes
      - memory.limit_in_byte
      - memory.stat.cache
      - cpuacct.usage
      - pids.current
      - pids.limit
      - status
    level: CONTAINER
    dependingitems:
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: container
  -
    type: appinstance
    keys:
      - pgid
      - machine_id
    labels:
      - exe_file
      - exec_file
      - tasks
    level: APPLICATION
    dependingitems:
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: container
            matches:
              -
                from: pgid
                to: pid
              -
                from: machine_id
                to: machine_id
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: appinstance
  -
    type: task
    keys:
      - pid
      - machine_id
    labels:
      - tgid
      - pgid
      - &task_name comm
      - exe_file
      - exec_file
      - major
      - minor
    name: *task_name
    metrics:
      - fork_count
      - task_io_wait_time_us
      - task_io_count
      - task_io_time_us
      - task_rchar_bytes
      - task_wchar_bytes
      - task_syscr_count
      - task_syscw_count
      - task_read_bytes
      - task_write_bytes
      - task_cancelled_write_bytes
      - task_hang_count
    level: PROCESS
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: appinstance
            matches:
              -
                from: pgid
                to: pgid
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: task
  -
    type: endpoint
    keys:
      - endpoint_type
      - s_addr
      - s_port
      - tgid
      - machine_id
    labels:
      - process_name
      - user_id
      - family
      - socket_type
      - protocol
    metrics:
      - listendrop
      - listen_overflow
      - passive_open
      - active_open
      - attempt_fail
      - abort_close
      - request_fail
      - rmem_schedule
      - tcp_oom
      - tcp_keepalive_timeout
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: task
            matches:
              -
                from: tgid
                to: tgid
              -
                from: tgid
                to: pid
              -
                from: machine_id
                to: machine_id
  -
    type: tcp_link
    keys:
      - server_ip
      - server_port
      - client_ip
      - tgid
      - role
      - machine_id
    labels:
      - protocol
    metrics:
      - rx_bytes
      - tx_bytes
      - packets_out
      - packets_in
      - retran_packets
      - lost_packets
      - link_count
      - tmout_count
      - rcv_que_full_count
      - snd_buf_limit_count
      - send_rsts
      - receive_rsts
    level: RPC
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: task
            matches:
              -
                from: tgid
                to: tgid
              -
                from: tgid
                to: pid
              -
                from: machine_id
                to: machine_id
      -
        id: is_server
        layer: direct
        toTypes:
          -
            type: ipvs_link
            matches: &lb_link_server_match
              -
                from: server_ip
                to: server_ip
              -
                from: server_port
                to: server_port
            requires: &lb_link_server_require
              -
                side: from
                label: role
                value: 0
          -
            type: nginx_link
            matches: *lb_link_server_match
            requires: *lb_link_server_require
          -
            type: haproxy_link
            matches: *lb_link_server_match
            requires: *lb_link_server_require
      -
        id: is_client
        layer: direct
        toTypes:
          -
            type: ipvs_link
            matches: &lb_link_client_match
              -
                from: client_ip
                to: client_ip
              -
                from: server_ip
                to: virtual_ip
              -
                from: server_port
                to: virtual_port
            requires: &lb_link_client_require
              -
                side: from
                label: role
                value: 1
          -
            type: nginx_link
            matches: *lb_link_client_match
            requires: *lb_link_client_require
          -
            type: haproxy_link
            matches: *lb_link_client_match
            requires: *lb_link_client_require
      -
        id: is_peer
        layer: direct
        toTypes:
          -
            type: tcp_link
            matches:
              -
                from: server_ip
                to: server_ip
              -
                from: server_port
                to: server_port
              -
                from: client_ip
                to: client_ip
  -
    type: ipvs_link
    keys: &lb_link_keys
      - server_ip
      - server_port
      - virtual_ip
      - virtual_port
      - local_ip
      - client_ip
      - pid
      - machine_id
    labels:
      - protocol
    metrics:
      - link_count
    level: LB
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: task
            matches: &lb_link_belong_task
              -
                from: pid
                to: pid
              -
                from: machine_id
                to: machine_id
  -
    type: nginx_link
    keys: *lb_link_keys
    metrics:
      - link_count
    level: LB
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: task
            matches: *lb_link_belong_task
  -
    type: haproxy_link
    keys: *lb_link_keys
    metrics:
      - link_count
    level: LB
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: task
            matches: *lb_link_belong_task
